/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AliasesRouteImport } from './routes/aliases'
import { Route as DomainsRouteImport } from './routes/domains'
import { Route as FailedDeliveriesRouteImport } from './routes/failed-deliveries'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RecipientsRouteImport } from './routes/recipients'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SubscriptionRouteImport } from './routes/subscription'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AliasesRoute = AliasesRouteImport.update({
  id: '/aliases',
  path: '/aliases',
  getParentRoute: () => rootRouteImport,
} as any)
const DomainsRoute = DomainsRouteImport.update({
  id: '/domains',
  path: '/domains',
  getParentRoute: () => rootRouteImport,
} as any)
const FailedDeliveriesRoute = FailedDeliveriesRouteImport.update({
  id: '/failed-deliveries',
  path: '/failed-deliveries',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipientsRoute = RecipientsRouteImport.update({
  id: '/recipients',
  path: '/recipients',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionRoute = SubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/aliases': typeof AliasesRoute
  '/domains': typeof DomainsRoute
  '/failed-deliveries': typeof FailedDeliveriesRoute
  '/login': typeof LoginRoute
  '/recipients': typeof RecipientsRoute
  '/settings': typeof SettingsRoute
  '/subscription': typeof SubscriptionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/aliases': typeof AliasesRoute
  '/domains': typeof DomainsRoute
  '/failed-deliveries': typeof FailedDeliveriesRoute
  '/login': typeof LoginRoute
  '/recipients': typeof RecipientsRoute
  '/settings': typeof SettingsRoute
  '/subscription': typeof SubscriptionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/aliases': typeof AliasesRoute
  '/domains': typeof DomainsRoute
  '/failed-deliveries': typeof FailedDeliveriesRoute
  '/login': typeof LoginRoute
  '/recipients': typeof RecipientsRoute
  '/settings': typeof SettingsRoute
  '/subscription': typeof SubscriptionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/aliases'
    | '/domains'
    | '/failed-deliveries'
    | '/login'
    | '/recipients'
    | '/settings'
    | '/subscription'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/aliases'
    | '/domains'
    | '/failed-deliveries'
    | '/login'
    | '/recipients'
    | '/settings'
    | '/subscription'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/aliases'
    | '/domains'
    | '/failed-deliveries'
    | '/login'
    | '/recipients'
    | '/settings'
    | '/subscription'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AliasesRoute: typeof AliasesRoute
  DomainsRoute: typeof DomainsRoute
  FailedDeliveriesRoute: typeof FailedDeliveriesRoute
  LoginRoute: typeof LoginRoute
  RecipientsRoute: typeof RecipientsRoute
  SettingsRoute: typeof SettingsRoute
  SubscriptionRoute: typeof SubscriptionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aliases': {
      id: '/aliases'
      path: '/aliases'
      fullPath: '/aliases'
      preLoaderRoute: typeof AliasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/domains': {
      id: '/domains'
      path: '/domains'
      fullPath: '/domains'
      preLoaderRoute: typeof DomainsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/failed-deliveries': {
      id: '/failed-deliveries'
      path: '/failed-deliveries'
      fullPath: '/failed-deliveries'
      preLoaderRoute: typeof FailedDeliveriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipients': {
      id: '/recipients'
      path: '/recipients'
      fullPath: '/recipients'
      preLoaderRoute: typeof RecipientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscription': {
      id: '/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof SubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AliasesRoute: AliasesRoute,
  DomainsRoute: DomainsRoute,
  FailedDeliveriesRoute: FailedDeliveriesRoute,
  LoginRoute: LoginRoute,
  RecipientsRoute: RecipientsRoute,
  SettingsRoute: SettingsRoute,
  SubscriptionRoute: SubscriptionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
